### ISSUE TITLE
Site not working, 404 error

### ISSUE THREAD

**Issue by deltaFigure** [Engarak/MiiShop#6]
Whenever i go the site at the assigned ip (192.168.0.113:8080 in this case)
i get this error:
https://i.imgur.com/nkJXeZR.png

Here's the console output if that helps.

Imported Settings
==================
2019-05-27T13:51:04 Checking for settings file
2019-05-27T13:51:04 settings file found, loading data

Name
----
port,8080,"webserver port"
debug,0,"a value with additional logging if needed in an error (0, no debugging, 1, with debugging).  Saved for futu...
backgroundPath,images/background.jpg,"Location of background image"
gameDB,3dsreleases.xml,"Location of database to match game library against (valid values: 3dsreleases.xml(default) o...
rebuild,0,"Forces a rebuild of the main page, only use this if the main page isn't working right or some games are n...

2019-05-27T13:51:04 No need to update web server configuration file. (Is this expected?)
2019-05-27T13:51:04 Creating folders as needed
Transcript started, output file is D:\delta\Documents\Miishop\logs\MiiShop_5-27-19-01_51_04.log
2019-05-27T13:51:04 Detecting Local IP address, this may take a few seconds
2019-05-27T13:51:08 Setting Webserver address to 192.168.0.113
2019-05-27T13:51:08 Managing Data
2019-05-27T13:51:08 Continuing, found 0 new *.cia files
2019-05-27T13:51:08 Database does not exist or is over a week old, downloading/updating game database
You cannot call a method on a null-valued expression.
At D:\delta\Documents\Miishop\miishop.ps1:885 char:8
+     if($gameDB.ToLower() -eq 'community.xml')
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

2019-05-27T13:51:08 Not re-creating mainpage as there are no new games to identify
2019-05-27T13:51:08 Adding firewalls exception if needed
2019-05-27T13:51:09 Inbound rule already exists, skipping
2019-05-27T13:51:09 Outbound rule already exists, skipping
2019-05-27T13:51:09 In just a moment you can browse miiShop by going to http:\\192.168.0.113:
2019-05-27T13:51:10 Webserver is started and running.

**Comment by deltaFigure** [comment]
I uploaded the console output to hastebin to make it more readable
https://hastebin.com/farosebude.coffeescript

**Comment by Engarak** [comment]
Let me first say, thanks for your patience. After I released the last version i took some time off for spending with the family, so I didn't get to this as quick as I wanted. I'm looking over your logs and seeing if I can figure out what's going on.  Give me a day or so, and I'll get you an answer.

**Comment by Engarak** [comment]
Actually, I have two thoughts.  First, if this is a new install please use [miiShop_install](https://github.com/Engarak/miiShop_Install/releases/tag/0.2.7) to setup things properly.  Otherwise if you're running an existing version that's been upgraded, try the steps below as I put in something to force a rebuild of the main.html file, which seems to have failed for you.  Let me know if you still have issues after this.

1. Go to the database folder, in the same location where start.bin is.  
1. Open the file in notepad (or any text file viewer, just not excel)
1. Find the line: (should be the last line)
    +  `rebuild,0,"Forces a rebuild of the main page, only use this if the main page isn't working right or some games are not being detected"`

    change it to
    + `rebuild,1,"Forces a rebuild of the main page, only use this if the main page isn't working right or some games are not being detected"`
1. Save the file
1. Right click on start.bat and choose run as administrator.  
1. After start.bat begins running, edit settings.csv and change 
    +  `rebuild,1,"Forces a rebuild of the main page, only use this if the main page isn't working right or some games are not being detected"`

    back to
    + `rebuild,0,"Forces a rebuild of the main page, only use this if the main page isn't working right or 
1. Save settings.csv

This will rebuild your main.html page (which I think is what failed out)

**Comment by Engarak** [comment]
I've fixed this in the new version (0.2.9) so this shouldn't be a reoccurring issue.
