### ISSUE TITLE
Miishop v0.2.9

### ISSUE THREAD

**Issue by Sabre8073** [Engarak/MiiShop#9]
Installed over v0.2.7 chose the upgrade option.

Everything went great but I was getting a timed out request when trying to download to 3ds and even tried to download to cell phone but again same issue.

Tried to do a clean install, deleted everything but my cias.

Now I get a welcome to nginx message instead of the main.html

Even when I leave the server running and manually open the main.html for my QRs I still get a timed out message.

What logs do I need to provide to be able to fix this issue?

**Comment by Engarak** [comment]
Well, that's not what I was hoping would happen!  Try the update button to ensure the latest version of the scripts are in place and then re-run steps 1 and 2.  If you still have issues from there, there is a logs folder in the root that I could analyze.  Arrange them by date and get me the latest two in pastebin and I'll look at the logs.

**Comment by Sabre8073** [comment]
Files you requested

[miiShop_4-14-20-10_43_52.log](https://github.com/Engarak/MiiShop/files/4482454/miiShop_4-14-20-10_43_52.log)
[makemain_4-14-20-10_43_35.log](https://github.com/Engarak/MiiShop/files/4482455/makemain_4-14-20-10_43_35.log)
[miiShop_4-14-20-10_30_40.log](https://github.com/Engarak/MiiShop/files/4482456/miiShop_4-14-20-10_30_40.log)

**Comment by Engarak** [comment]
So based on your makemain and miiShop logs, things look good.  I have a few questions that may help find out what's going on:

- If you look in the miiShop folder, look in the bin\nginx\html folder, do you see main.html?  If so, when you open that with a browser (or just double click it) does it show anything? 
- When you start miiShop and start up the web server, what's the address it tries to connect to?  Does the page show if you add main.html to the end of it?  I know it was hanging loading (or just showing a white page) before, but want to check.
- After you start miiShop and the page doesn't come up what happens if you try http://localhost/main.html or http://127.0.0.1/main.html?
- miiShop should work if you have a VPN connected (it works fine for me with a VPN, but configurations differ I know), but if you have one running, can you test with it off?
- Do you have any other web servers running on that computer?  If you're not sure, the answer is usually no, but it's possible you need to go into the settings and change the port miiShop is running?

Sorry it's not answers yet, but hopefully we'll find something quickly.

**Comment by Sabre8073** [comment]
If you look in the miiShop folder, look in the bin\nginx\html folder, do you see main.html? If so, when you open that with a browser (or just double click it) does it show anything?

**Yes there is a main.html and it opens the miishop webpage but when I try to download from there while the server is running I get a timeout error**

When you start miiShop and start up the web server, what's the address it tries to connect to? Does the page show if you add main.html to the end of it? I know it was hanging loading (or just showing a white page) before, but want to check.

**192.168.56.1; No, the only thing listed in the address bar is the ipaddress**

After you start miiShop and the page doesn't come up what happens if you try http://localhost/main.html or http://127.0.0.1/main.html?

**It will access the miishop webpage but again when trying to install with QR the requests time out**

miiShop should work if you have a VPN connected (it works fine for me with a VPN, but configurations differ I know), but if you have one running, can you test with it off?

**I do have a vpn but I do not have it currently running while using this program**

Do you have any other web servers running on that computer? If you're not sure, the answer is usually no, but it's possible you need to go into the settings and change the port miiShop is running?

**I am not running any other servers**

**Comment by Engarak** [comment]
Ok, so it sounds like everything is right except some configuration options.  Can you send me your nginx config? You can find it from in the miiShop root folder, look in /bin/nginx/conf folder for it.  Also, to ensure it made the QR codes right can you send me the QR directory from /bin/nginx/html/qr as well?  Also, what version of Windows are you running at this point?  I just want to make sure if I test things I match your configuration.  Thanks for your patience while I try to figure out what's going on.

**Comment by Engarak** [comment]
No reply in months, closing.  Will re-open with further details.
